name: CI

on:
  push:
  pull_request:
    branches:
      -main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Check linting errors
        run: npm lint
        
      
  
